#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# the "app_lucky_number" route name is not important yet


home :
  path: /
  controller: App\Controller\HomeController::index

#reservation :
#  path: /Réservation
#  controller: App\Controller\ReservationController::index

#testimony:
#  path: /Témoignages
#  controller: App\Controller\TestimonyController::index

about:
  path: /nous-connaitre
  controller: App\Controller\AboutController::index

#blog:
#  path: /Blog
#  controller: App\Controller\BlogController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::contact

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

newuser:
  path: /newuser
  controller: App\Controller\UsersController::createUser

editprofile:
  path: /compte
  controller: App\Controller\UsersController::editprofileUser

admin:
  path: /admin
  controller: App\Controller\AdminController::index
